query Admin__core_files__show(
  $cursor: Int
  $first: Int
  $sortBy: ShowCoreFilesSortByArgs
  $last: Int
  $search: String
) {
  admin__core_files__show(
    cursor: $cursor
    first: $first
    sortBy: $sortBy
    last: $last
    search: $search
  ) {
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
    edges {
      count_uses
      created
      dir_folder
      extension
      file_alt
      file_name
      file_name_original
      file_size
      height
      id
      mimetype
      security_key
      user {
        id
        name
        name_seo
      }
      width
    }
  }
}
