import type { LocaleConfig } from "../lib/i18n/types";
import type {
  JsonValue,
  VitNodeConfig,
  VitNodePublicConfig,
  VitNodePublicPlugin,
} from "./types";

import { DEFAULT_LOCALE_PREFIX, DEFAULT_TIME_ZONE } from "./define";
import { VitNodeConfigError } from "./errors";
import { toSingleQuotedLiteral, toTypeScriptLiteral } from "./literal";
import { findNonSerializable, toSerializable } from "./serializable";

const PUBLIC_TYPES_SPECIFIER = "@vitnode/core/config";

const serializableSection = <T>(section: string, value: T): T => {
  const finding = findNonSerializable(value);

  if (finding) {
    throw new VitNodeConfigError(
      "public-options-not-serializable",
      `\`${section}\` is written into the generated public config, so it has to be plain JSON: at ${finding.path}, ${finding.reason}.`,
    );
  }

  return toSerializable(value) as T;
};

const publicLocale = ({ code, enabled, name }: LocaleConfig): LocaleConfig => ({
  code,
  ...(enabled === undefined ? {} : { enabled }),
  name,
});

const publicPlugin = (
  plugin: VitNodeConfig["plugins"][number],
): VitNodePublicPlugin => ({
  pluginId: plugin.pluginId,
  ...(plugin.publicOptions === undefined
    ? {}
    : { publicOptions: plugin.publicOptions as JsonValue }),
});

export const projectPublicConfig = (
  config: VitNodeConfig,
): VitNodePublicConfig => {
  const web = config.web?.public ?? {};
  const { defaultLocale, localePrefix, locales, timeZone } = config.app.i18n;
  const { shortTitle, title } = config.app.metadata;

  return {
    debug: web.debug ?? false,
    ...(web.editor === undefined
      ? {}
      : { editor: serializableSection("web.public.editor", web.editor) }),
    i18n: {
      defaultLocale,
      localePrefix: localePrefix ?? DEFAULT_LOCALE_PREFIX,
      locales: locales.map(publicLocale),
      timeZone: timeZone ?? DEFAULT_TIME_ZONE,
    },
    metadata: { ...(shortTitle === undefined ? {} : { shortTitle }), title },
    plugins: config.plugins.map(publicPlugin),
    ...(web.theme === undefined
      ? {}
      : { theme: serializableSection("web.public.theme", web.theme) }),
  };
};

export const pluginPublicOptions = <T extends JsonValue = JsonValue>(
  config: Pick<VitNodePublicConfig, "plugins">,
  pluginId: string,
): T | undefined =>
  config.plugins.find(plugin => plugin.pluginId === pluginId)?.publicOptions as
    T | undefined;

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: \`src/vitnode.config.ts\`.
// It holds the browser-safe projection of that config and nothing else - the
// root config, with its database provider and secrets, is never imported by a
// browser.

import type { VitNodePublicConfig } from ${toSingleQuotedLiteral(PUBLIC_TYPES_SPECIFIER)}
`;

export const generatePublicConfigSource = (
  publicConfig: VitNodePublicConfig,
): string => {
  const codes = publicConfig.i18n.locales
    .filter(locale => locale.enabled !== false)
    .map(locale => toSingleQuotedLiteral(locale.code));
  const localeUnion =
    codes.length === 0 ? "never" : [...new Set(codes)].join(" | ");

  return `${HEADER}
export const vitNodePublicConfig = ${toTypeScriptLiteral(publicConfig)} satisfies VitNodePublicConfig

export type VitNodeLocale = ${localeUnion}
`;
};
