// @vitest-environment node
import { describe, expect, it } from "vitest";

import {
  defineApiRuntime,
  defineVitNodeConfig,
  defineWebRuntime,
} from "./define";
import { definePluginFactory } from "./plugin";
import {
  generatePublicConfigSource,
  pluginPublicOptions,
  projectPublicConfig,
} from "./public";

const DATABASE_URL = "postgresql://root:super-secret@db.internal:5432/vitnode";

const blog = definePluginFactory<
  { postsPerPage: number; webhookSecret: string },
  { postsPerPage: number }
>({
  defaults: { postsPerPage: 20, webhookSecret: "whsec_private_value" },
  pluginId: "@acme/blog",
  toPublicOptions: ({ postsPerPage }) => ({ postsPerPage }),
});

const quiet = definePluginFactory({ pluginId: "@acme/quiet" });

const config = defineVitNodeConfig({
  api: defineApiRuntime(({ env }) => ({
    dbProvider: { url: env.POSTGRES_URL ?? DATABASE_URL } as never,
    storage: { adapter: { secretKey: "sb_secret_value" } as never },
  })),
  app: {
    i18n: {
      defaultLocale: "en",
      locales: [
        { code: "en", name: "English" },
        { code: "pl", name: "Polski" },
        { code: "de", enabled: false, name: "Deutsch" },
      ],
      timeZone: "UTC",
    },
    metadata: { shortTitle: "Fx", title: "Fixture" },
  },
  plugins: [blog({ postsPerPage: 7 }), quiet()],
  web: defineWebRuntime({
    public: {
      debug: true,
      editor: { emojis: [{ emojis: [], label: "Brand" }] },
      theme: { defaultTheme: "dark" },
    },
    server: () => ({ packageMessages: {} }),
  }),
});

describe("projectPublicConfig", () => {
  const publicConfig = projectPublicConfig(config);

  it("is an explicit allowlist", () => {
    expect(Object.keys(publicConfig).sort()).toEqual([
      "debug",
      "editor",
      "i18n",
      "metadata",
      "plugins",
      "theme",
    ]);
    expect(Object.keys(publicConfig.i18n).sort()).toEqual([
      "defaultLocale",
      "localePrefix",
      "locales",
      "timeZone",
    ]);
  });

  it("carries the browser-safe values", () => {
    expect(publicConfig).toMatchObject({
      debug: true,
      editor: { emojis: [{ emojis: [], label: "Brand" }] },
      i18n: { defaultLocale: "en", localePrefix: "as-needed", timeZone: "UTC" },
      metadata: { shortTitle: "Fx", title: "Fixture" },
      theme: { defaultTheme: "dark" },
    });
    expect(publicConfig.i18n.locales.map(locale => locale.code)).toEqual([
      "en",
      "pl",
      "de",
    ]);
  });

  it("lists every plugin with only its sanitized public options", () => {
    expect(publicConfig.plugins).toEqual([
      { pluginId: "@acme/blog", publicOptions: { postsPerPage: 7 } },
      { pluginId: "@acme/quiet" },
    ]);
    expect(pluginPublicOptions(publicConfig, "@acme/blog")).toEqual({
      postsPerPage: 7,
    });
    expect(pluginPublicOptions(publicConfig, "@acme/quiet")).toBeUndefined();
  });

  it("contains no server value at all", () => {
    const serialized = JSON.stringify(publicConfig);

    for (const secret of [
      "super-secret",
      "sb_secret_value",
      "whsec_private_value",
      "dbProvider",
      "storage",
      "webhookSecret",
      "api",
    ]) {
      expect(serialized).not.toContain(secret);
    }
  });

  it("does not run the API or web-server runtime", () => {
    let calls = 0;
    const lazy = defineVitNodeConfig({
      api: defineApiRuntime(() => {
        calls += 1;

        return { dbProvider: {} as never };
      }),
      app: config.app,
      web: defineWebRuntime({
        server: () => {
          calls += 1;

          return {};
        },
      }),
    });

    projectPublicConfig(lazy);

    expect(calls).toBe(0);
  });

  it("defaults debug to false and omits absent sections", () => {
    const minimal = projectPublicConfig(
      defineVitNodeConfig({ app: config.app }),
    );

    expect(minimal.debug).toBe(false);
    expect("editor" in minimal).toBe(false);
    expect("theme" in minimal).toBe(false);
    expect(minimal.plugins).toEqual([]);
  });

  it("refuses a theme that is not plain JSON", () => {
    expect(() =>
      projectPublicConfig(
        defineVitNodeConfig({
          app: config.app,
          web: defineWebRuntime({
            public: { theme: { value: { dark: () => "x" } } as never },
          }),
        }),
      ),
    ).toThrow(/web\.public\.theme/);
  });
});

describe("generatePublicConfigSource", () => {
  const source = generatePublicConfigSource(projectPublicConfig(config));

  it("is a generated, typed module", () => {
    expect(source.startsWith("/* eslint-disable */")).toBe(true);
    expect(source).toContain("generated by VitNode");
    expect(source).toContain("do not format it");
    expect(source).toContain(
      "import type { VitNodePublicConfig } from '@vitnode/core/config'",
    );
    expect(source).toContain("export const vitNodePublicConfig = {");
    expect(source).toContain("} satisfies VitNodePublicConfig");
  });

  it("derives the locale union from the enabled locales", () => {
    expect(source).toContain("export type VitNodeLocale = 'en' | 'pl'");
    expect(source).not.toContain("'de' |");
  });

  it("is byte-identical for the same input and ends with one newline", () => {
    expect(generatePublicConfigSource(projectPublicConfig(config))).toBe(
      source,
    );
    expect(source.endsWith("\n")).toBe(true);
    expect(source.endsWith("\n\n")).toBe(false);
  });

  it("writes plugin ids and public options, and nothing from the server", () => {
    expect(source).toContain("pluginId: '@acme/blog'");
    expect(source).toContain("postsPerPage: 7");
    expect(source).not.toContain("webhookSecret");
    expect(source).not.toContain("super-secret");
    expect(source).not.toContain("dbProvider");
  });

  it("quotes keys that are not identifiers", () => {
    const withOddKey = generatePublicConfigSource({
      ...projectPublicConfig(config),
      plugins: [
        { pluginId: "@acme/odd", publicOptions: { "data-attr": "x'y" } },
      ],
    });

    expect(withOddKey).toContain("'data-attr': 'x\\'y'");
  });
});
