// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI

type IntlMessages = typeof import('@/plugins/core/langs/en.json') &
  typeof import('@/plugins/welcome/langs/en.json') &
  // ! === IMPORT ===
  typeof import('@/plugins/admin/langs/en.json');
