query Core_members__profiles($first: Int, $findByIds: [String!]) {
  core_members__show(first: $first, findByIds: $findByIds) {
    edges {
      avatar_color
      group {
        name {
          language_id
          value
        }
      }
      id
      joined
      name
      posts
    }
  }
}
