// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
'use client';

import { NotFoundView } from 'vitnode-frontend/views/theme/views/not-found';

export default function NotFound() {
  return <NotFoundView />;
}
