query Admin__forum_forums__show($first: Int, $cursor: Int, $parentId: Int) {
  admin__forum_forums__show(
    first: $first
    cursor: $cursor
    parent_id: $parentId
  ) {
    edges {
      id
      description {
        language_code
        value
      }
      name {
        language_code
        value
      }
      position
      created
      children {
        created
        description {
          language_code
          value
        }
        id
        name {
          language_code
          value
        }
        position
        _count {
          children
        }
      }
      _count {
        children
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
