query Forum_forums__admin__show($first: Int, $cursor: String, $parentId: String) {
  forum_forums__admin__show(first: $first, cursor: $cursor, parent_id: $parentId) {
    edges {
      id
      description {
        id_language
        value
      }
      name {
        id_language
        value
      }
      position
      views
      created
      children {
        created
        description {
          id_language
          value
        }
        id
        name {
          id_language
          value
        }
        position
        views
        _count {
          children
        }
      }
      _count {
        children
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
