// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import {
  OverviewDevPluginAdminView,
  OverviewDevPluginAdminViewProps,
} from 'vitnode-frontend/admin/core/plugins/views/dev/overview/overview';

export default function Page(props: OverviewDevPluginAdminViewProps) {
  return <OverviewDevPluginAdminView {...props} />;
}
