// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import {
  MainSettingsCoreAdminView,
  generateMetadataMainSettingsCoreAdmin,
} from 'vitnode-frontend/admin/core/settings/main/main-settings-core-admin-view';

export const generateMetadata = generateMetadataMainSettingsCoreAdmin;

export default function Page() {
  return <MainSettingsCoreAdminView />;
}
