/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from one input: the plugins configured in
// `src/vitnode.config.ts`, and which of them export an `admin/nav` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
//
// `adminNav` below is what the AdminCP shell and the `/_admin` loader read.
// It is derived here rather than in an app's own `src/lib`, so a generated
// application has no wrapper to keep in step with this file.

import type { AdminNavPluginSource } from '@vitnode/core/lib/plugin'

import { adminNavBundle } from '@vitnode/core/tanstack/admin'

import { adminNav as adminNav0 } from '@vitnode/blog/admin/nav'
import { adminNav as adminNav1 } from '@vitnode/example/admin/nav'


export const pluginAdminNav = [
  adminNav0, // @vitnode/blog
  adminNav1, // @vitnode/example
] satisfies AdminNavPluginSource[]

export const adminNav = adminNavBundle({ plugins: pluginAdminNav })
