/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from one input: `src/vitnode.config.ts`.
// It holds the browser-safe projection of that config and nothing else - the
// root config, with its database provider and secrets, is never imported by a
// browser.

import type { VitNodePublicConfig } from '@vitnode/core/config'

export const vitNodePublicConfig = {
  debug: false,
  editor: {
    emojis: [
      {
        emojis: [
          {
            name: 'vitnode',
            src: '/logo_vitnode_icon.svg',
            tags: [
              'logo',
              'brand',
            ],
          },
        ],
        label: 'VitNode',
      },
    ],
  },
  i18n: {
    defaultLocale: 'en',
    localePrefix: 'as-needed',
    locales: [
      {
        code: 'en',
        name: 'English',
      },
      {
        code: 'pl',
        name: 'Polski',
      },
    ],
    timeZone: 'UTC',
  },
  metadata: {
    shortTitle: 'VitNode',
    title: 'VitNode',
  },
  plugins: [
    {
      pluginId: '@vitnode/blog',
      publicOptions: {
        postsPerPage: 20,
      },
    },
    {
      pluginId: '@vitnode/example',
    },
  ],
  theme: {
    defaultTheme: 'system',
  },
} satisfies VitNodePublicConfig

export type VitNodeLocale = 'en' | 'pl'
