// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI

import { Module } from '@nestjs/common';

import { WelcomeModule } from './welcome/welcome.module';
// ! === IMPORT ===

@Module({
  imports: [
    WelcomeModule,
    // ! === MODULE ===
  ],
})
export class PluginsModule {}
