query Core_members__show__search($search: String, $first: Int) {
  core_members__show(search: $search, first: $first) {
    edges {
      avatar_color
      group {
        id
        name {
          language_code
          value
        }
      }
      id
      name
    }
  }
}
