// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import { SignInAdminView } from 'vitnode-frontend/admin/sign-in/sign-in-admin-view';

export default function Page() {
  return <SignInAdminView />;
}
