query Core_languages__show($first: Int, $last: Int, $cursor: Int) {
  core_languages__show(first: $first, last: $last, cursor: $cursor) {
    edges {
      code
      default
      enabled
      id
      name
      protected
      timezone
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
