query Admin__sessions__authorization {
  admin__sessions__authorization {
    user {
      email
      id
      name_seo
      is_admin
      is_mod
      name
      newsletter
      avatar_color
      avatar {
        id
        dir_folder
        name
      }
      group {
        name {
          language_code
          value
        }
        id
      }
    }
    rebuild_required {
      themes
      langs
      plugins
    }
    version
    nav {
      code
      nav {
        code
        href
        icon
      }
    }
  }
}
