query Forum_forums__show {
  forum_forums__show {
    edges {
      id
      description {
        id_language
        value
      }
      name {
        id_language
        value
      }
      children {
        id
        name {
          id_language
          value
        }
        children {
          id
          name {
            id_language
            value
          }
        }
        description {
          id_language
          value
        }
      }
    }
  }
}
