query Forum_forums__show_item {
  forum_forums__show {
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
    edges {
      id
      description {
        id_language
        value
      }
      name {
        id_language
        value
      }
      children {
        id
        name {
          id_language
          value
        }
        children {
          id
          name {
            id_language
            value
          }
        }
        description {
          id_language
          value
        }
      }
    }
  }
}
