query Forum_forums__show_item($cursor: Int, $first: Int, $last: Int, $forumId: Int!) {
  forum_forums__show(ids: [$forumId]) {
    edges {
      id
      description {
        language_code
        value
      }
      name {
        language_code
        value
      }
      children {
        id
        name {
          language_code
          value
        }
        children {
          id
          name {
            language_code
            value
          }
        }
        description {
          language_code
          value
        }
      }
      permissions {
        can_create
      }
    }
  }
  forum_topics__show(cursor: $cursor, first: $first, last: $last, forum_id: $forumId) {
    edges {
      created
      id
      title {
        language_code
        value
      }
      user {
        id
        name_seo
        name
        avatar_color
        avatar {
          dir_folder
          name
        }
        group {
          id
          name {
            language_code
            value
          }
        }
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
