query Forum_forums__show_item($cursor: String, $first: Int, $last: Int, $forumId: String!) {
  forum_forums__show(ids: [$forumId]) {
    edges {
      id
      description {
        id_language
        value
      }
      name {
        id_language
        value
      }
      children {
        id
        name {
          id_language
          value
        }
        children {
          id
          name {
            id_language
            value
          }
        }
        description {
          id_language
          value
        }
      }
    }
  }
  forum_topics__show(cursor: $cursor, first: $first, last: $last, forum_id: $forumId) {
    edges {
      content {
        value
        id_language
      }
      created
      id
      updated
      title {
        id_language
        value
      }
      author {
        avatar {
          created
          description
          extension
          file_size
          id
          member_id
          mimetype
          module
          module_id
          name
          position
          url
        }
        id
        name
        avatar_color
        group {
          id
          name {
            id_language
            value
          }
        }
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
