query Forum_forums__show($cursor: String, $first: Int) {
  forum_forums__show(cursor: $cursor, first: $first) {
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
    edges {
      id
      description {
        id_language
        value
      }
      name {
        id_language
        value
      }
      children {
        id
        name {
          id_language
          value
        }
        children {
          id
          name {
            id_language
            value
          }
        }
        description {
          id_language
          value
        }
      }
    }
  }
}
