query Forum_forums__show($lastPostsArgs: LastPostsShowForumForumsArgs) {
  forum_forums__show(last_posts_args: $lastPostsArgs) {
    edges {
      id
      description {
        language_code
        value
      }
      name {
        language_code
        value
      }
      children {
        id
        name {
          language_code
          value
        }
        children {
          id
          name {
            language_code
            value
          }
        }
        description {
          language_code
          value
        }
        _count {
          total_posts
          total_topics
          topics
          posts
        }
        last_posts {
          edges {
            id
            user {
              avatar {
                dir_folder
                id
                name
              }
              avatar_color
              group {
                id
                name {
                  language_code
                  value
                }
              }
              id
              name
              name_seo
            }
            topic {
              id
              title {
                language_code
                value
              }
            }
            created
          }
        }
      }
    }
  }
}
