// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import {
  NavDevPluginAdminView,
  NavDevPluginAdminViewProps,
} from 'vitnode-frontend/admin/core/plugins/views/dev/nav/nav';

export default function Page(props: NavDevPluginAdminViewProps) {
  return <NavDevPluginAdminView {...props} />;
}
