// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import { DashboardCoreAdminView } from 'vitnode-frontend/admin/core/dashboard/dashboard-core-admin-view';

export default function Page() {
  return <DashboardCoreAdminView />;
}
