query Admin__core_plugins__download_check($code: String!) {
  admin__core_plugins__download_check(code: $code) {
    admin_pages
    admin_templates
    databases
    graphql_mutations
    graphql_queries
    hooks
    language
    pages
    pages_container
    templates
    default_page
  }
}
