query Core_plugins__admin__show(
  $cursor: Int
  $first: Int
  $last: Int
  $sortBy: [ShowAdminPluginsSortByArgs!]
) {
  core_plugins__admin__show(cursor: $cursor, first: $first, last: $last, sortBy: $sortBy) {
    edges {
      author
      author_url
      code
      default
      description
      enabled
      id
      name
      protected
      support_url
      created
      version
      version_code
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
