import adminContentCreateDarkSmall from '@/site/home/assets/admin-content-create-dark-800.webp'
import adminContentCreateDark from '@/site/home/assets/admin-content-create-dark.webp'
import adminContentCreateLightSmall from '@/site/home/assets/admin-content-create-light-800.webp'
import adminContentCreateLight from '@/site/home/assets/admin-content-create-light.webp'
import adminDashboardDarkSmall from '@/site/home/assets/admin-dashboard-dark-800.webp'
import adminDashboardDark from '@/site/home/assets/admin-dashboard-dark.webp'
import adminDashboardLightSmall from '@/site/home/assets/admin-dashboard-light-800.webp'
import adminDashboardLight from '@/site/home/assets/admin-dashboard-light.webp'
import adminIntegrationsDarkSmall from '@/site/home/assets/admin-integrations-dark-800.webp'
import adminIntegrationsDark from '@/site/home/assets/admin-integrations-dark.webp'
import adminIntegrationsLightSmall from '@/site/home/assets/admin-integrations-light-800.webp'
import adminIntegrationsLight from '@/site/home/assets/admin-integrations-light.webp'
import adminRolesDarkSmall from '@/site/home/assets/admin-roles-dark-800.webp'
import adminRolesDark from '@/site/home/assets/admin-roles-dark.webp'
import adminRolesLightSmall from '@/site/home/assets/admin-roles-light-800.webp'
import adminRolesLight from '@/site/home/assets/admin-roles-light.webp'
import publicLoginDarkSmall from '@/site/home/assets/public-login-dark-800.webp'
import publicLoginDark from '@/site/home/assets/public-login-dark.webp'
import publicLoginLightSmall from '@/site/home/assets/public-login-light-800.webp'
import publicLoginLight from '@/site/home/assets/public-login-light.webp'

export interface ScreenImage {
  large: string
  small: string
}

export interface Screen {
  alt: string
  dark: ScreenImage
  light: ScreenImage
  title: string
  url: string
}

export const SCREEN_SIZE = { height: 866, width: 1600 }
export const SCREEN_SMALL_WIDTH = 800

export const SCREENS = {
  contentEditor: {
    alt: 'The Create Article screen generated by the Content Engine, with title, friendly URL and rich text fields that each have a language selector, plus cover image and settings panels.',
    dark: { large: adminContentCreateDark, small: adminContentCreateDarkSmall },
    light: {
      large: adminContentCreateLight,
      small: adminContentCreateLightSmall,
    },
    title: 'Content editor',
    url: 'yourcommunity.com/admin/content/blog/articles/create',
  },
  dashboard: {
    alt: 'The AdminCP dashboard with a sidebar listing Core, Blog and Example plugin sections, a private notes widget and a send-notification widget.',
    dark: { large: adminDashboardDark, small: adminDashboardDarkSmall },
    light: { large: adminDashboardLight, small: adminDashboardLightSmall },
    title: 'Dashboard',
    url: 'yourcommunity.com/admin',
  },
  integrations: {
    alt: 'The Integrations screen showing status cards for AI, WebSocket, Redis, email, storage, cron jobs, content preview and queue tasks.',
    dark: { large: adminIntegrationsDark, small: adminIntegrationsDarkSmall },
    light: {
      large: adminIntegrationsLight,
      small: adminIntegrationsLightSmall,
    },
    title: 'Integrations',
    url: 'yourcommunity.com/admin/core/system/integrations',
  },
  login: {
    alt: 'The public sign-in page with email and password fields and Discord, Google and Facebook buttons.',
    dark: { large: publicLoginDark, small: publicLoginDarkSmall },
    light: { large: publicLoginLight, small: publicLoginLightSmall },
    title: 'Sign-in page',
    url: 'yourcommunity.com/login',
  },
  roles: {
    alt: 'The Roles screen listing Moderator, Administrator, Member and Guest roles with member counts and update dates.',
    dark: { large: adminRolesDark, small: adminRolesDarkSmall },
    light: { large: adminRolesLight, small: adminRolesLightSmall },
    title: 'Roles',
    url: 'yourcommunity.com/admin/core/users/roles',
  },
} satisfies Record<string, Screen>

export type ScreenKey = keyof typeof SCREENS
