// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
// ! If you remove this then default page plugin will not work
import React from 'react';
import { getSessionData } from 'vitnode-frontend/graphql/get-session-data';
import { generateMetadataDefaultPage } from 'vitnode-frontend/views/theme/views/default-page';

export const generateMetadata = generateMetadataDefaultPage;

export default async function Page() {
  const {
    core_sessions__authorization: { plugin_default },
  } = await getSessionData();

  const PageFromTheme = React.lazy(async () =>
    import(`@/plugins/${plugin_default}/templates/default-page`).then(
      module => ({
        default: module.default,
      }),
    ),
  );

  return <PageFromTheme />;
}
