query Core_middleware {
  core_languages__show {
    edges {
      default
      code
      id
      name
      timezone
      enabled
    }
  }
  core_themes__show {
    edges {
      id
      name
    }
  }
}
