// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI

import { defineConfig } from 'drizzle-kit';

import { DATABASE_ENVS } from '@/database';

export default defineConfig({
  dialect: 'postgresql',
  dbCredentials: DATABASE_ENVS,
  schema: './src/plugins/core/admin/database/schema/*.ts',
  out: './src/plugins/core/admin/database/migrations/',
});
