query Forum_topics__show(
  $id: Int!
  $first: Int
  $cursor: Int
  $forumPostsShowFirst2: Int
  $last: Int
) {
  forum_topics__show(id: $id, first: $first) {
    edges {
      content {
        language_code
        value
      }
      created
      id
      locked
      title {
        language_code
        value
      }
      user {
        avatar_color
        avatar {
          id
          dir_folder
          name
        }
        group {
          id
          name {
            language_code
            value
          }
        }
        id
        name_seo
        name
      }
      forum {
        id
        name {
          language_code
          value
        }
      }
    }
  }
  forum_posts__show(topic_id: $id, cursor: $cursor, first: $forumPostsShowFirst2, last: $last) {
    edges {
      __typename
      ... on ShowPostsForums {
        content {
          value
          language_code
        }
        id
        user {
          avatar_color
          avatar {
            id
            dir_folder
            name
          }
          group {
            id
            name {
              language_code
              value
            }
          }
          id
          name_seo
          name
        }
        created
      }
      ... on ShowPostsForumsMetaTags {
        action
        id
        user {
          avatar_color
          avatar {
            id
            dir_folder
            name
          }
          group {
            id
            name {
              language_code
              value
            }
          }
          id
          name_seo
          name
        }
        created
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
