query Forum_posts__show_more(
  $id: Int!
  $limit: Int!
  $sortBy: ShowPostsForumsSortingEnum
  $page: Int
) {
  forum_posts__show(
    topic_id: $id
    limit: $limit
    sortBy: $sortBy
    page: $page
  ) {
    edges {
      __typename
      ... on ShowPostsForums {
        content {
          value
          language_code
        }
        user {
          avatar_color
          avatar {
            id
            dir_folder
            name
          }
          group {
            id
            name {
              language_code
              value
            }
          }
          id
          name_seo
          name
        }
        created
        post_id
      }
      ... on ShowPostsForumsMetaTags {
        action
        user {
          avatar_color
          avatar {
            id
            dir_folder
            name
          }
          group {
            id
            name {
              language_code
              value
            }
          }
          id
          name_seo
          name
        }
        created
        action_id
      }
    }
    pageInfo {
      totalCount
      hasNextPage
    }
  }
}
