query Short_show_groups_admin_members($first: Int, $search: String) {
  show_admin_groups(first: $first, search: $search) {
    edges {
      id
      name {
        id_language
        value
      }
    }
  }
}
