query Show_admin_groups(
  $first: Int
  $cursor: String
  $search: String
  $sortBy: [ShowAdminGroupsSortByArgs!]
  $last: Int
) {
  show_admin_groups(first: $first, cursor: $cursor, search: $search, sortBy: $sortBy, last: $last) {
    pageInfo {
      count
      endCursor
      hasNextPage
      startCursor
      totalCount
      hasPreviousPage
    }
    edges {
      created
      updated
      id
      usersCount
      protected
      guest
      name {
        id_language
        value
      }
    }
  }
}
