query Admin__forum_forums__show($first: Int, $cursor: Int, $parentId: Int) {
  admin__forum_forums__show(
    first: $first
    cursor: $cursor
    parent_id: $parentId
  ) {
    edges {
      id
      description {
        language_code
        value
      }
      name {
        language_code
        value
      }
      position
      created
      children {
        created
        description {
          language_code
          value
        }
        id
        name {
          language_code
          value
        }
        position
        _count {
          posts
          topics
          total_posts
          total_topics
        }
      }
      permissions {
        can_all_create
        can_all_read
        can_all_reply
        can_all_view
        can_all_download_files
        groups {
          can_create
          can_read
          can_reply
          can_view
          can_download_files
          id
        }
      }
      _count {
        posts
        topics
        total_posts
        total_topics
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
