query Show_forum_forums($first: Int, $cursor: String) {
  show_forum_forums(first: $first, cursor: $cursor) {
    edges {
      id
      is_category
      description {
        id_language
        value
      }
      name {
        id_language
        value
      }
      position
      views
      created
      _count {
        children
      }
    }
    pageInfo {
      count
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      totalCount
    }
  }
}
