// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import {
  EmailSettingsAdminView,
  generateMetadataEmailSettingsAdmin,
} from 'vitnode-frontend/admin/core/settings/email/email-settings-admin-view';

export const generateMetadata = generateMetadataEmailSettingsAdmin;

export default function Page() {
  return <EmailSettingsAdminView />;
}
