// ! DO NOT TOUCH THIS FILE!!! IT IS GENERATED BY VITNODE-CLI
import React from 'react';
import 'vitnode-frontend/admin/css';

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
