import type { ResolvedAdminNavModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

/** Where the generated file imports its type from. */
const TYPES_SPECIFIER = "@vitnode/core/lib/plugin";

/** Where the generated file imports the projection's one consumer from. */
const RUNTIME_SPECIFIER = "@vitnode/core/tanstack/admin";

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`, and which of them export an \`admin/nav\` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
//
// \`adminNav\` below is what the AdminCP shell and the \`/_admin\` loader read.
// It is derived here rather than in an app's own \`src/lib\`, so a generated
// application has no wrapper to keep in step with this file.

import type { AdminNavPluginSource } from '${TYPES_SPECIFIER}'

import { adminNavBundle } from '${RUNTIME_SPECIFIER}'
`;

/**
 * The doc comment on the export, written into the generated file.
 *
 * Long, and on purpose: this is the module somebody opens when the AdminCP
 * sidebar is missing a plugin, and the answer - "that plugin does not export
 * `admin/nav`" - is not guessable from an array of two entries.
 */
const BODY_DOC = `

export const pluginAdminNav`;

/** The derived export, identical in every generated file. */
const BUNDLE = `
export const adminNav = adminNavBundle({ plugins: pluginAdminNav })
`;

const importLines = (modules: ResolvedAdminNavModule[]): string =>
  modules
    .map(
      (module, index) =>
        `import { adminNav as adminNav${index} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n");

/**
 * The source of an app's AdminCP navigation projection.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Sorted by plugin id here rather than trusted to arrive that way, so "same
 * configuration, same bytes" is a property of this function rather than a
 * promise about how it is called. The aliases are positional for the same
 * reason: a plugin id is not an identifier, and deriving one would mean two
 * plugins whose ids differ only in punctuation colliding silently.
 */
export const generateAdminNavSource = (
  modules: readonly ResolvedAdminNavModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  if (sorted.length === 0) {
    return `${HEADER}${BODY_DOC}: AdminNavPluginSource[] = []\n${BUNDLE}`;
  }

  const entries = sorted
    .map((module, index) => `  adminNav${index}, // ${module.pluginId}`)
    .join("\n");

  return `${HEADER}\n${importLines(sorted)}\n${BODY_DOC} = [\n${entries}\n] satisfies AdminNavPluginSource[]\n${BUNDLE}`;
};
