query Core_staff_administrators__admin__show {
  core_staff_administrators__admin__show {
    edges {
      created
      id
      unrestricted
      user_or_group {
        __typename
        ... on GroupUser {
          id
          groupName: name {
            id_language
            value
          }
        }
        ... on User {
          avatar {
            created
            description
            extension
            file_size
            id
            member_id
            mimetype
            module
            module_id
            name
            position
            url
          }
          avatar_color
          cover {
            created
            description
            extension
            file_size
            id
            member_id
            mimetype
            module
            module_id
            name
            position
            url
          }
          group {
            id
            name {
              id_language
              value
            }
          }
          id
          name
        }
      }
    }
  }
}
